Repository Linkta-org/core, pull requests merged in 2024-08, with the labels that each got.

#364 Feature/Ensure Idempotency for UserInput Submission
  .github/docs/API_DESIGN_DOCUMENTATION_V1.md
  client/components/user-input/UserInputForm.tsx
  client/hooks/useCreateLinktaFlowMutation.ts
  client/hooks/useThrottle.ts
  server/controllers/userInputController.ts
  server/middleware/IdempotencyMiddleware.ts
  server/middleware/rateLimiterMiddleware.ts
  server/mocks/userId.ts
  server/models/GeminiModel.ts
  server/models/IdempotencyRecordModel.ts
  server/routes/userInputRouter.ts
  server/services/idempotencyService.ts
  server/types/idempotencyRecord.d.ts
  server/utils/customErrors.ts
  server/utils/helpers.ts
Labels: sprint-9, MVP Final Push, fullstack

#369 Incorporates Loader state UI during LLM processing
  client/components/common/Loader.tsx
  client/components/layout/UserInputList.tsx
  client/components/user-input/UserInputForm.tsx
  client/features/output-visualization-page/OutputVisualizationPage.tsx
  client/stores/LoadingStore.ts
  client/styles/Loader.module.css
Labels: frontend, MVP Final Push

#373 Adds Functionality for Popular Topics to Generate a New LinktaFlow
  client/components/user-input/PopularTopics.tsx
  client/components/user-input/UserInputForm.tsx
  client/stores/UserInputStore.ts
  client/styles/UserInputView.module.css
Labels: frontend, MVP Final Push

#375 Refactor: Replace Throttle with Debounce for LinktaFlow Generation
  client/components/user-input/PopularTopics.tsx
  client/components/user-input/UserInputForm.tsx
  client/hooks/useDebounce.ts
Labels: frontend, refactor

#376 Hotfix: SnackBarNotification Errors
  client/components/common/SideNavDrawer.tsx
  client/features/auth-pages/SignInPage.tsx
  client/hooks/useNotification.ts
  client/stores/NotificationStore.ts
Labels: bug, frontend, hotfix

#381 bugfix: moved Loader logic from UserInputForm to UserInputView
  client/components/user-input/UserInputForm.tsx
  client/components/user-input/UserInputView.tsx
Labels: bug, frontend
