Repository Linkta-org/core, pull requests merged in 2024-06, with the labels that each got.

#115 Feature/UserInput submission UI
  client/components/common/PromptInputForm.tsx
  client/components/layout/MainLayout.tsx
  client/features/prompt-input-page/PromptInputPage.tsx
  client/styles/MainLayout.css
  server/routes/userInput.ts
  server/server.ts
Labels: frontend, UI/UX, sprint-0

#68 LINKTA-99 & 202: Authentication Process Flow and Decision Making
  .github/decisions/Authentication_flow.md
Labels: documentation

#140 adds favicon coverage to most browsers & devices
  client/assets/favicons/android-chrome-192x192.png
  client/assets/favicons/android-chrome-512x512.png
  client/assets/favicons/apple-touch-icon.png
  client/assets/favicons/favicon-16x16.png
  client/assets/favicons/favicon-32x32.png
  client/assets/favicons/favicon.ico
  client/assets/favicons/mstile-150x150.png
  client/assets/favicons/safari-pinned-tab.svg
  client/browserconfig.xml
  client/index.html
  client/manifest.json
  package-lock.json
Labels: enhancement, frontend, design, sprint-1

#151 Chore: add .env.example file
  config/.env.example
Labels: documentation

#153 152 implement api endpoint for retrieving user input history
  .github/docs/API_DESIGN_DOCUMENTATION_V1.md
  mocks/index.ts
  mocks/userId.ts
  package.json
  server/controllers/userInputController.ts
  server/models/UserInputModel.ts
  server/models/UserModel.ts
  server/routes/userInput.ts
  server/types/datamodels.d.ts
  tsconfig.json
Labels: backend

#180 Fixes a possible memory leak in the useMatchMedia custom hook
  client/components/layout/MainLayout.tsx
  client/hooks/useMatchMedia.ts
  client/hooks/useMediaMatch.ts
  package-lock.json
Labels: frontend, UI/UX, sprint-1, refactor, hotfix

#162 159 create user input history component with clickable links
  client/components/common/PaginationButton.tsx
  client/components/common/SideNavDrawer.tsx
  client/components/common/SkeletonList.tsx
  client/components/layout/Footer.tsx
  client/components/layout/PaginationControls.tsx
  client/components/layout/UserInputHistory.tsx
  client/components/layout/UserInputList.tsx
  client/components/layout/userInputConstants.ts
  client/config/axios.ts
  client/hooks/useUserInputList.ts
  client/services/userInputService.ts
  client/utils/placeholder.ts
  mocks/index.ts
  mocks/userInputList.ts
  server/controllers/userInputController.ts
  server/server.ts
Labels: frontend, urgent, unblocking, sprint-1

#192 Added Turbo Console; Added Vite Plugin Checker; removed ENV variables from npm scripts
  client/vite.config.js
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement, frontend, UI/UX, spike, configuration

#147 Feature/133 implement custom edge component for linktaflow according to figma design
  client/features/output-visualization-page/OutputVisualizationPage.tsx
  client/features/output-visualization-page/components/ConnectionLine.tsx
  client/features/output-visualization-page/components/Flow.tsx
  client/features/output-visualization-page/components/LinktaFlowEdge.tsx
  client/features/output-visualization-page/components/LinktaNode.tsx
  client/features/output-visualization-page/components/TreeVisualizationBox.tsx
  client/features/prompt-input-page/PromptInputPage.tsx
  client/styles/MainLayout.css
  client/utils/getEdgeParams.ts
Labels: frontend

#194 173 update system design doc according to recent changes implementation backend
  .github/docs/API_DESIGN_DOCUMENTATION_V1.md
  .github/docs/MVP_SYSTEM_DESIGN_DOCUMENTATION.md
  .github/docs/assets/data-ERD.png
Labels: documentation, backend

#195 Feature/integrate react hook form with userinput
  client/components/prompt-input/PromptInputForm.tsx
  package-lock.json
  package.json
Labels: enhancement, frontend, UI/UX, sprint-3

#209 feature/title adds useDocumentTitle custom hook to set document title & sample usage #105
  client/components/prompt-input/PromptInputPage.tsx
  client/features/auth-pages/SignInPage.tsx
  client/features/help-and-feedback-page/HelpAndFeedbackPage.tsx
  client/features/home-page/HomePage.tsx
  client/features/settings-page/Settings.tsx
  client/hooks/useDocumentTitle.ts
Labels: good first issue, frontend, configuration, sprint-2

#183 182 set up css module for application & refactored userinputhistory feature styling
  client/components/layout/ListItemMenu.tsx
  client/components/layout/MainLayout.tsx
  client/components/layout/OptionsMenu.tsx
  client/components/layout/PaginationButton.tsx
  client/components/layout/PaginationControls.tsx
  client/components/layout/SkeletonList.tsx
  client/components/layout/UserInputHistory.tsx
  client/components/layout/UserInputList.tsx
  client/hooks/useInputHistory.ts
  client/index.html
  client/main.tsx
  client/services/userInputService.ts
  client/stores/userDrawerStore.ts
  client/styles/SideNavDrawer.css
  client/styles/layout/OptionsMenu.module.css
  client/styles/layout/PaginationButton.module.css
  client/styles/layout/PaginationControls.module.css
  client/styles/layout/SkeletonList.module.css
  client/styles/layout/UserInputHistory.module.css
  client/styles/layout/UserInputList.module.css
  client/types/cssModules.d.ts
  client/utils/customTheme.ts
  client/vite.config.js
  mocks/CustomThemeTestComponent.module.css
  mocks/CustomThemeTestComponent.tsx
Labels: frontend, styling

#211 Updated userinputschema & associated implementation
  client/components/layout/UserInputList.tsx
  client/hooks/useInputHistory.ts
  mocks/userInputList.ts
  server/controllers/userInputController.ts
  server/models/UserInputModel.ts
  server/types/datamodels.d.ts
Labels: frontend, backend

#229 Feature: Complete /v1/inputs routes
  .github/docs/API_DESIGN_DOCUMENTATION_V1.md
  client/mocks/linktaFlow.ts
  client/mocks/userId.ts
  client/services/userInputService.ts
  server/controllers/userInputController.ts
  server/mocks/index.ts
  server/mocks/userId.ts
  server/mocks/userInputList.ts
  server/models/LinktaFlowModel.ts
  server/models/UserInputModel.ts
  server/package-lock.json
  server/package.json
  server/routes/userInputRouter.ts
  server/services/aiService.ts
  server/services/linktaFlowService.ts
  server/services/userInputService.ts
  server/types/index.ts
  server/zod/sanitizeInput.ts
  server/zod/userInputSchemas.ts
  server/zod/userInputValidation.ts
Labels: documentation, backend

#237 Feature/Implemented React Query for user input history fetching & pagination
  client/components/layout/PaginationControls.tsx
  client/components/layout/UserInputHistory.tsx
  client/components/layout/userInputConstants.ts
  client/hooks/useInfiniteInputQuery.ts
  client/hooks/useInputHistory.ts
  client/services/userInputService.ts
  client/utils/constants.ts
Labels: frontend

#261 Hotfix & Improve Pre-commit hook and lint-staged configuration; Solve Bug #259
  .husky/pre-commit
  client/.lintstagedrc.json
  lint-staged.config.js
  package.json
  server/.lintstagedrc.json
Labels: documentation, enhancement, configuration, hotfix, Infrastructure

#257 Server-side Authentication Support
  .husky/pre-commit
  .vscode/settings.json
  package.json
  server/middleware/firebaseAuthMiddleware.ts
  server/package-lock.json
  server/package.json
  server/routes/linktaFlowRouter.ts
  server/routes/userInputRouter.ts
  server/server.ts
  server/utils/environment.ts
Labels: backend

#263 Implement delete functionality for delete button on the operations menu
  client/components/layout/UserInputList.tsx
  client/services/userInputService.ts
Labels: frontend

#264 250 implement react query for input title updates
  client/components/layout/UserInputList.tsx
  client/hooks/useInfiniteInputQuery.ts
  client/hooks/useInputHistory.ts
  client/hooks/useUpdateInputTitleMutation.ts
  client/services/userInputService.ts
  client/stores/UserInputStore.ts
  client/types/LinktaFlow.d.ts
  client/types/UserInput.d.ts
  client/types/UserInput.ts
  client/types/index.ts
Labels: frontend

#271 Feature/rate limiting
  server/middleware/rateLimiterMiddleware.ts
  server/package-lock.json
  server/package.json
  server/server.ts
Labels: enhancement, backend, urgent, configuration

#272 implemented react query for fetching linktaflow
  client/components/layout/UserInputList.tsx
  client/features/output-visualization-page/OutputVisualizationPage.tsx
  client/features/output-visualization-page/components/Flow.tsx
  client/features/output-visualization-page/components/LinktaNode.tsx
  client/hooks/useFetchLinktaFlow.ts
  client/hooks/useInfiniteInputQuery.ts
  client/routes/privateRoutes.tsx
  client/services/userInputService.ts
  server/server.ts
Labels: frontend

#270 add firebase auth; add google auth; add RQ mutations; fix husky; add …
  client/.eslintrc.json
  client/components/user-input/UserInputForm.tsx
  client/d.ts
  client/features/auth-pages/SignInPage.tsx
  client/features/auth-pages/SignUpPage.tsx
  client/features/auth-pages/UnauthorizedLayout.tsx
  client/firebase/firebaseConfig.ts
  client/hooks/googleAuthMutation.ts
  client/hooks/newUserInputMutation.ts
  client/hooks/useAuth.ts
  client/hooks/useUpdateInputTitleMutation.ts
  client/hooks/userWithEmailAndPasswordMutation.ts
  client/package-lock.json
  client/package.json
  client/routes/ProtectedRoute.tsx
  client/stores/UserInputStore.ts
  client/tsconfig.json
  client/types/UserInput.d.ts
  package-lock.json
  package.json
  scripts/nuke_and_install.js
  scripts/nuke_and_install.sh
  server/package-lock.json
  server/server.ts
Labels: frontend, configuration

#278 Hot Fix: No Authorization Header on Axios Request for UserHistory Component
  client/components/user-input/UserInputForm.tsx
  client/hooks/useInfiniteInputQuery.ts
  client/hooks/userWithEmailAndPasswordMutation.ts
  client/routes/publicRoutes.tsx
  client/routes/unprotectedRoutes.tsx
  server/middleware/firebaseAuthMiddleware.ts
Labels: bug, frontend, backend, UI/UX
