Repository Linkta-org/core, pull requests merged in 2024-07, with the labels that each got.

#274 Enahnced Skeleton for Userinputhistory
  client/components/layout/SkeletonList.tsx
  client/components/layout/UserInputHistory.tsx
  client/components/layout/UserInputHistorySkeleton.tsx
  client/components/layout/UserInputList.tsx
  client/styles/layout/SkeletonList.module.css
  client/styles/layout/UserInputHistorySkeleton.module.css
Labels: frontend, refactor

#279 Bugfix/auth + router + pagination
  client/config/axios.ts
  client/hooks/useInfiniteInputQuery.ts
  client/routes/publicRoutes.tsx
  client/routes/unprotectedRoutes.tsx
  server/middleware/firebaseAuthMiddleware.ts
Labels: bug

#267 91: Set up unit testing environments
  client/__tests__/placeholder.test.ts
  client/package-lock.json
  client/package.json
  client/tests/unit/placeholder.unit.test.ts
  client/tsconfig.json
  client/vite.config.js
  server/package-lock.json
  server/package.json
  server/tests/unit/placeholder.unit.test.ts
  server/tsconfig.json
  server/vitest.config.ts
  test/client/components/Tree.test.ts
  test/client/containers/NavBar.test.ts
  test/client/src/app/Entry.test.tsx
  test/client/utils/base.test.ts
  test/server/controllers/authenticationController.test.ts
  test/server/models/gemini.test.ts
  test/server/routes/user.test.ts
  test/server/utils/base.test.ts
Labels: testing, configuration

#269 implemented react query for deleting userinput
  client/components/layout/UserInputList.tsx
  client/hooks/useDeleteInputMutation.ts
  client/services/userInputService.ts
Labels: frontend

#273 implemented react query hook for updating linktaflow
  client/components/layout/MainLayout.tsx
  client/components/layout/UserInputList.tsx
  client/features/output-visualization-page/components/Flow.tsx
  client/hooks/useUpdateLinktaFlowMutation.ts
  client/types/LinktaFlow.d.ts
Labels: frontend

#283 #225 Implement Firebase Authentication with Password and Email
  client/components/layout/MainLayout.tsx
  client/components/layout/UserInputList.tsx
  client/features/auth-pages/SignInPage.tsx
  client/features/auth-pages/SignUpPage.tsx
  client/hooks/useCreateUserWithEmailAndPassword.ts
  client/hooks/useSignInWithEmailAndPassword.ts
  client/hooks/useSignInWithGitHub.ts
  client/hooks/useSignOut.ts
Labels: frontend

#284 Update home-page format; Sign Out button; Correct router path names
  client/components/common/SideNavDrawer.tsx
  client/components/layout/MainLayout.tsx
  client/features/auth-pages/PasswordRecoverPage.tsx
  client/features/auth-pages/PasswordUpdatePage.tsx
  client/features/auth-pages/SignInPage.tsx
  client/features/auth-pages/SignUpPage.tsx
  client/features/auth-pages/UnauthorizedLayout.tsx
  client/features/home-page/HomePage.tsx
  client/features/home-page/Homepage.module.css
  client/routes/ProtectedRoute.tsx
  client/routes/publicRoutes.tsx
  client/styles/Homepage.module.css
  client/styles/layout/AuthStyles.module.css
  server/middleware/firebaseAuthMiddleware.ts
  server/server.ts
  server/utils/log4js.config.json
Labels: bug, enhancement, frontend, design, chore

#286 Update image and icon paths to comply with Vite conventions
  client/components/layout/UserInputList.tsx
  client/features/auth-pages/SignInPage.tsx
  client/features/auth-pages/SignUpPage.tsx
  client/features/auth-pages/UnauthorizedLayout.tsx
  client/features/home-page/HomePage.tsx
  client/index.html
  client/manifest.json
  client/public/Linkta-Landing.png
  client/public/favicons/android-chrome-192x192.png
  client/public/favicons/android-chrome-512x512.png
  client/public/favicons/apple-touch-icon.png
  client/public/favicons/favicon-16x16.png
  client/public/favicons/favicon-32x32.png
  client/public/favicons/favicon.ico
  client/public/favicons/mstile-150x150.png
  client/public/favicons/safari-pinned-tab.svg
  client/public/github-icon.png
  client/public/google-icon.png
  client/public/linkta-logo-amber.png
  client/public/linkta-logo-web.png
  client/public/tree-golden.webp
  client/public/tree-grove.webp
  client/public/tree-night.webp
  client/public/tree-pedestal.webp
  client/public/tree-urban.webp
  client/public/tree-winter.webp
  client/public/white-tree.png
  client/styles/MainLayout.css
  client/styles/layout/UnauthorizedLayout.module.css
  client/tsconfig.json
Labels: bug, frontend, UI/UX, chore

#293 Foundation for Developer Onboarding document
  .github/docs/DEVELOPER_ONBOARDING.md
  .github/docs/assets/screenshot-firebase-config.png
  .github/docs/assets/screenshot-firebase-key.png
Labels: documentation

#303 Correct Linkta logo png reference path in MainLayout; Improve server logging config
  client/components/layout/MainLayout.tsx
  server/utils/log4js.config.json
Labels: bug, frontend, urgent

#305 Update auth middleware and environment files
  server/middleware/firebaseAuthMiddleware.ts
  server/utils/environment.ts
Labels: bug, enhancement, backend, configuration

#304 Update DEVELOPER_ONBOARDING.md
  .github/docs/DEVELOPER_ONBOARDING.md
Labels: documentation, enhancement

#308 Add files via upload
  .github/docs/assets/screenshot-firebase-config.png
Labels: documentation

#310 Update DEVELOPER_ONBOARDING.md
  .github/docs/DEVELOPER_ONBOARDING.md
Labels: documentation

#309 Fix 285 ensure correct rendering of linktaflow in react flow component
  client/features/output-visualization-page/components/Flow.tsx
  server/controllers/linktaFlowController.ts
  server/models/LinktaFlowModel.ts
Labels: frontend, backend

#306 290 Provide UI for users to delete input + 125 Provide UI for Users to Rename The Input + 121 Implement functionality for users to Regenerate a new LinktaFlow
  .github/docs/API_DESIGN_DOCUMENTATION_V1.md
  client/components/layout/DeleteDialog.tsx
  client/components/layout/MainLayout.tsx
  client/components/layout/RenameDialog.tsx
  client/components/layout/UserInputList.tsx
  client/components/user-input/UserInputForm.tsx
  client/features/output-visualization-page/components/Flow.tsx
  client/hooks/newUserInputMutation.ts
  client/hooks/useCreateLinktaFlowMutation.ts
  client/hooks/useDeleteInputMutation.ts
  client/hooks/useInfiniteInputQuery.ts
  client/hooks/useUpdateInputTitleMutation.ts
  client/mocks/linktaFlow.ts
  client/mocks/userInputList.ts
  client/stores/SideNavDrawerStore.ts
  client/styles/layout/DeleteDialog.module.css
  client/styles/layout/RenameDialog.module.css
  client/tsconfig.json
  client/types/LinktaFlow.d.ts
  client/types/UserInput.d.ts
  client/types/snackBar.d.ts
  client/utils/helpers.ts
  client/validators/userInputSchemas.ts
  client/zod/sanitizeUserInput.ts
  server/controllers/linktaFlowController.ts
  server/controllers/userInputController.ts
  server/server.ts
  server/services/linktaFlowService.ts
Labels: frontend

#307 Replace Mock User IDs with Real User IDs and Implement New User Profile Management
  client/components/common/SideNavDrawer.tsx
  client/components/layout/MainLayout.tsx
  client/features/auth-pages/SignInPage.tsx
  client/features/auth-pages/SignUpPage.tsx
  client/hooks/useCreateUserProfileMutation.ts
  client/hooks/useFetchUserProfile.ts
  client/hooks/useSignOut.ts
  client/main.tsx
  client/types/user.d.ts
  server/controllers/userController.ts
  server/controllers/userInputController.ts
  server/middleware/firebaseAuthMiddleware.ts
  server/models/UserModel.ts
  server/routes/linktaFlowRouter.ts
  server/routes/userInputRouter.ts
  server/routes/userRouter.ts
  server/server.ts
  server/services/aiService.ts
  server/services/userInputService.ts
  server/services/userService.ts
  server/types/datamodels.d.ts
  server/types/user.d.ts
Labels: frontend, backend

#311 #240 forgot/reset password
  client/components/common/SnackBarNotification.tsx
  client/features/auth-pages/ForgotPasswordPage.tsx
  client/features/auth-pages/PasswordRecoverPage.tsx
  client/features/auth-pages/PasswordUpdatePage.tsx
  client/features/auth-pages/SignInPage.tsx
  client/features/auth-pages/SignUpPage.tsx
  client/hooks/useGetPasswordResetLinkMutation.ts
  client/hooks/useUpdatePasswordMutation.ts
  client/routes/publicRoutes.tsx
  client/validators/validateUserPassword.ts
  client/validators/validateUseremail.ts
Labels: frontend

#320 Bugfix/Handle OAuth User Sign-In on Sign-Up Page to Prevent Duplicate User Profile Creation
  client/features/auth-pages/SignInPage.tsx
Labels: bug, frontend

#322 232 & 317: Create contribution guidelines, remove .vscode directory
  .github/docs/CONTRIBUTING.md
  .vscode/settings.json
Labels: documentation

#323 Updated GitHub auth hook; Renamed Google auth hook
  client/features/auth-pages/SignInPage.tsx
  client/features/auth-pages/SignUpPage.tsx
  client/hooks/useSignInWithGitHub.ts
  client/hooks/useSignInWithGoogle.ts
Labels: bug, enhancement, frontend, UI/UX

#324 Developer Onboarding documentation updates
  .github/docs/DEVELOPER_ONBOARDING.md
Labels: documentation

#326 Prepare to update environment variables for deployment
  client/config/axios.ts
  client/types/vite-env.d.ts
  client/vite.config.js
  server/server.ts
Labels: frontend, backend, configuration, Infrastructure

#316 Implement undo/redo functionality for linktaflow
  client/features/output-visualization-page/components/Flow.tsx
  client/features/output-visualization-page/components/UndoAndRedo.tsx
  client/package-lock.json
  client/package.json
  client/stores/LinktaFlowStore.ts
  client/types/LinktaFlow.d.ts
Labels: frontend, UI/UX

#300 Implement 404 and Error pages
  client/components/layout/MainLayout.tsx
  client/features/auth-pages/UnauthorizedLayout.tsx
  client/features/error-pages/ErrorPage.tsx
  client/features/error-pages/NotFoundPage.tsx
  client/features/not-found-page/NotFoundPage.tsx
  client/routes/index.tsx
  client/styles/ErrorPage.module.css
  client/styles/NotFoundPage.module.css
Labels: frontend

#330 Refactor ErrorHandlerMiddleware, delete createError and add Error Classes
  server/controllers/genAiController.ts
  server/controllers/linktaFlowController.ts
  server/controllers/userController.ts
  server/controllers/userInputController.ts
  server/middleware/errorHandling.ts
  server/middleware/firebaseAuthMiddleware.ts
  server/middleware/rateLimiterMiddleware.ts
  server/middleware/validationMiddleware.ts
  server/models/GeminiModel.ts
  server/server.ts
  server/services/aiService.ts
  server/services/linktaFlowService.ts
  server/services/userInputService.ts
  server/services/userService.ts
  server/utils/customErrors.ts
Labels: backend, refactor

#334 Dynamic CORS origins
  client/features/auth-pages/SignInPage.tsx
  server/middleware/dynamicOriginsMiddleware.ts
  server/server.ts
  server/utils/log4js.config.json
Labels: enhancement, backend, configuration
