Repository Linkta-org/core, pull requests merged in 2024-09, with the labels that each got.

#394 Doc: Decision Log for Adopting Factory Function-based Dependency Injection Design Pattern
  .github/decisions/API_Design_Pattern_Decision_Log.md
Labels: documentation

#392 refactor: resets undo/redo states when selecting another LinktaFLow
  client/features/output-visualization-page/components/UndoAndRedo.tsx
  client/stores/LinktaFlowStore.ts
  client/stores/UndoRedoStore.ts
  client/styles/UndoAndRedo.module.css
Labels: bug, frontend

#395 Refactor: Improve UserInputList Structure and UX
  client/components/layout/UserInputList.tsx
  client/utils/errorHandler.ts
  client/utils/helpers.ts
Labels: frontend, refactor

#377 Login error resolution / simplification
  client/components/common/SideNavDrawer.tsx
  client/components/layout/MainLayout.tsx
  client/components/layout/StaticLayout.tsx
  client/components/layout/UserInputList.tsx
  client/config/axios.ts
  client/config/firebaseConfig.ts
  client/features/auth-pages/SignInPage.tsx
  client/features/auth-pages/SignUpPage.tsx
  client/features/auth-pages/UnauthorizedLayout.tsx
  client/features/output-visualization-page/components/Flow.tsx
  client/hooks/useCreateUserProfileMutation.ts
  client/hooks/useCreateUserWithEmailAndPassword.ts
  client/hooks/useFetchUserProfile.ts
  client/hooks/useSignInWithEmailAndPassword.ts
  client/hooks/useSignInWithGitHub.ts
  client/hooks/useSignInWithGoogle.ts
  client/hooks/useSignOut.ts
  client/hooks/useUserCrudOperations.ts
  client/hooks/useWatchAuthenticatedState.ts
  client/routes/ProtectedRoute.tsx
  client/routes/index.tsx
  client/styles/SideNavDrawer.module.css
  client/styles/StaticLayout.module.css
  client/styles/layout/UnauthorizedLayout.module.css
  client/tests/unit/App.unit.test.tsx
  client/types/user.d.ts
  client/validators/validateUseremail.ts
  server/controllers/genAiController.ts
  server/controllers/userController.ts
  server/controllers/userInputController.ts
  server/middleware/dynamicOriginsMiddleware.ts
  server/middleware/errorHandling.ts
  server/middleware/firebaseAuthMiddleware.ts
  server/models/GeminiModel.ts
  server/models/LinktaFlowModel.ts
  server/models/UserInputModel.ts
  server/models/UserModel.ts
  server/package-lock.json
  server/package.json
  server/routes/linktaFlowRouter.ts
  server/routes/userInputRouter.ts
  server/routes/userRouter.ts
  server/server.ts
  server/services/aiService.ts
  server/services/userInputService.ts
  server/services/userService.ts
  server/types/datamodels.d.ts
  server/types/errorHandling.d.ts
  server/types/user.d.ts
  server/utils/log4js.config.json
  server/utils/typeChecker.ts
Labels: bug, frontend, backend, unblocking, MVP Final Push, fullstack

#399 Update/developer onboarding
  .github/docs/DEVELOPER_ONBOARDING.md
Labels: documentation

#406 Fix Manifest Error and Add Title Tag
  client/index.html
Labels: bug
