Repository Linkta-org/core, pull requests merged in 2024-03, with the labels that each got.

#12 LINKTA-21 Lint rules
  .eslintrc.json
  .gitignore
  .prettierrc.json
  package-lock.json
  package.json
Labels: good practice

#14 Feature/react-naming-convention-guide
  REACT_NAMING_CONVENTIONS_GUIDE.md
Labels: documentation

#16 Chore: Feature/frontend install
  package-lock.json
  package.json
Labels: frontend, unblocking

#13 LINKTA-3: Set up file structure
  .github/actions/deploy_to_staging/action.yaml
  .github/workflows/staging.yaml
  .gitignore
  client/assets/fav.ico
  client/components/Tree.tsx
  client/containers/NavBar.tsx
  client/src/app/Entry.tsx
  client/styles/base.css
  client/types/components.d.ts
  client/utils/base.ts
  config/webpack.config.js
  server/controllers/authenticationController.ts
  server/models/gemini.ts
  server/routes/user.ts
  server/utils/base.ts
  test/client/components/Tree.test.ts
  test/client/containers/NavBar.test.ts
  test/client/src/app/Entry.test.tsx
  test/client/utils/base.test.ts
  test/server/controllers/authenticationController.test.ts
  test/server/models/gemini.test.ts
  test/server/routes/user.test.ts
  test/server/utils/base.test.ts
Labels: urgent

#15 LINKTA-71 Document AI research
  .github/docs/AI_Research_Notes.md
Labels: documentation

#21 Proposal for Security Best Practices Documentation
  .github/docs/SECURITY_BEST_PRACTICES.md
Labels: documentation

#23 LINKTA-23: Establish practices for file organization/names, and variable names
  .github/docs/NAMING_CONVENTIONS_GUIDE.md
  REACT_NAMING_CONVENTIONS_GUIDE.md
Labels: documentation

#19 LINKTA-20: Backend Dependencies Added
  package-lock.json
  package.json
Labels: backend

#27 LINKTA-116: Update naming conventions doc
  .github/docs/Commit_Message_Guidelines.md
  .github/docs/NAMING_CONVENTIONS_GUIDE.md
Labels: documentation

#29 LINKTA-114: Uninstall Next.js and install React Router
  package-lock.json
  package.json
Labels: frontend

#32 LINKTA-124: Change Pull_Request_Template location and file name
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#28 LINKTA-118: Update docs file names according to best naming practices
  .github/PULL_REQUEST_TEMPLATE.md
  .github/docs/COMMIT_MESSAGE_GUIDE.md
  .github/docs/NAMING_CONVENTIONS_GUIDE.md
Labels: documentation

#36 LINKTA-144: Remove Landing Page from Core Repo
  client/features/landing-page/LandingPage.tsx
  client/features/landing-page/components/CallToActionField.tsx
  client/features/landing-page/components/MarketingContent.tsx
  client/features/landing-page/components/WaitingListSubmissionForm.tsx
  client/public/index.html
Labels: frontend

#37 LINKTA-94: Back-end sends information to front-end
  package.json
  server/middleware/errorHandling.ts
  server/server.ts
  server/types/index.ts
  server/types/middleware.d.ts
  server/utils/base.ts
  server/utils/environment.ts
  tsconfig.json
Labels: backend

#42 LINKTA-131: Create MainLayout Component Structure
  client/components/layout/main-layout/MainLayout.tsx
Labels: frontend

#33 LINKTA-122: Add Linting to Github Actions
  .eslintrc.json
  .github/workflows/staging.yaml
  package-lock.json
  package.json
Labels: backend

#35 Linkta-90-Create-User-Schema/Linkta-93-Create-Node-Schema
  server/models/NodeModel.ts
  server/models/UserModel.ts
  server/models/gemini.ts
  server/types/datamodels.d.ts
Labels: backend

#45 LINKTA-163: docs/create decisions folder and move related md
  .github/decisions/AI_Research_Notes.md
Labels: documentation

#51 LINKTA-179: unify package.json files & update scripts
  .gitignore
  client/App.jsx
  client/App.tsx
  client/index.html
  client/index.ts
  client/main.jsx
  client/main.tsx
  client/package-lock.json
  client/package.json
  client/vite.config.js
  package-lock.json
  package.json
Labels: bug, urgent

#43 LINKTA-136: Set up React Router
  client/App.tsx
  client/features/error-pages/NotFoundPage.tsx
  client/routes/index.tsx
  client/routes/privateRoutes.tsx
  client/routes/publicRoutes.tsx
Labels: frontend, unblocking

#50 LINKTA-162: docs: Create basic template for writing research or decision documentation
  .github/decisions/Decision_Documentation_Template.md
Labels: documentation

#54 LINKTA-170: Update MainLayout structure to work with React Router
  client/components/layout/main-layout/MainLayout.tsx
  client/components/layout/main-layout/header/LinktaLogoWithText.tsx
  client/components/layout/main-layout/header/TopNavigationBar.tsx
  client/components/layout/main-layout/layoutConfig.ts
  client/hooks/useDynamicNavigation.ts
Labels: frontend

#65 feature/LINKTA-206-Setup-ErrorPage
  client/features/error-pages/ErrorPage.tsx
Labels: frontend

#47 LINKTA-133: Implement footer component
  client/components/layout/main-layout/footer/Footer.tsx
  client/components/layout/main-layout/layoutConfig.ts
  package-lock.json
Labels: frontend

#63 feature/LINKTA-182-Setup-HomePage
  client/features/home-page/HomePage.tsx
  client/features/home-page/components/HomePageMainHero.tsx
  client/features/home-page/components/HomePageTreeVisualizationPanel.tsx
Labels: frontend

#62 Feature/linkta 194 set up private routing for authenticated access
  client/hooks/useAuth.ts
  client/routes/ProtectedRoute.tsx
  client/routes/index.tsx
  client/routes/privateRoutes.tsx
  client/routes/public-routes/authRoutes.tsx
  client/routes/public-routes/publicRoutes.tsx
  client/routes/publicRoutes.tsx
Labels: frontend
