Repository Linkta-org/core, pull requests merged in 2024-10, with the labels that each got.

#405 Bugfix: React List Key Issue
  server/controllers/linktaFlowController.ts
  server/models/LinktaFlowModel.ts
  server/services/linktaFlowService.ts
  server/types/datamodels.d.ts
Labels: bug

#401 Refactor: updated user input from left sidebar with tooltip
  client/components/layout/UserInputList.tsx
Labels: enhancement, good first issue, frontend, UI/UX, MVP Final Push

#402 feat(#385): Consistent yellow pill buttons
  client/features/error-pages/ErrorPage.tsx
  client/features/error-pages/NotFoundPage.tsx
  client/styles/ErrorPage.module.css
  client/styles/NotFoundPage.module.css
  client/styles/UserInputView.module.css
  client/styles/layout/AuthStyles.module.css
  client/styles/layout/DeleteDialog.module.css
  client/styles/layout/RenameDialog.module.css
Labels: good first issue, frontend, styling, refactor, MVP Final Push

#400 Adds PrivacyPolicy and TermsOfService components and cursor behavior on hyperlinks
  client/features/auth-pages/ForgotPasswordPage.tsx
  client/features/auth-pages/PasswordUpdatePage.tsx
  client/features/auth-pages/SignInPage.tsx
  client/features/auth-pages/SignUpPage.tsx
  client/features/privacy-policy/PrivacyPolicy.tsx
  client/features/terms-of-service/TermsOfService.tsx
  client/routes/publicRoutes.tsx
  client/styles/PrivacyPolicy.module.css
  client/styles/TermsOfService.module.css
Labels: frontend, MVP Final Push

#398 Logging imrovements; scheduled backups
  .github/docs/DEVELOPER_ONBOARDING.md
  .gitignore
  client/features/auth-pages/BackOffice.tsx
  client/package-lock.json
  client/package.json
  client/routes/privateRoutes.tsx
  client/styles/BackOffice.module.css
  package-lock.json
  server/controllers/logsController.ts
  server/controllers/userController.ts
  server/controllers/userInputController.ts
  server/middleware/errorHandling.ts
  server/models/UserModel.ts
  server/package-lock.json
  server/package.json
  server/routes/logsRouter.ts
  server/server.ts
  server/services/logsService.ts
  server/utils/log4js.config.json
  server/utils/loggerConfig.ts
  server/utils/loggerScheduledTasks.ts
Labels: enhancement, backend

#411 Added _redirects file to /client
  client/_redirects
Labels: bug, frontend, MVP Final Push

#425 Dynamic Node Connection Feature + Flow Refactoring
  client/features/output-visualization-page/components/Flow.tsx
Labels: frontend, UI/UX, refactor

#410 feat: add Settings Page
  client/components/common/SideNavDrawer.tsx
  client/features/settings-page/Settings.tsx
  client/hooks/useUserCrudOperations.ts
  client/styles/SettingsPage.module.css
  client/validators/validateUserDisplayName.ts
  server/controllers/userController.ts
Labels: frontend, backend

#424 Refactor UserInputList and Options Menu Anchor for Better Accessibility & UI/UX
  client/components/common/LinktaDialog.tsx
  client/components/layout/OptionsMenu.tsx
  client/components/layout/RenameDialog.tsx
  client/components/layout/UserInputList.tsx
  client/styles/LinktaDialog.module.css
  client/styles/layout/DeleteDialog.module.css
  client/styles/layout/OptionsMenu.module.css
  client/styles/layout/RenameDialog.module.css
  client/styles/layout/UserInputList.module.css
  client/utils/customTheme.ts
Labels: bug, frontend, UI/UX, refactor, MVP Final Push

#428 Docs: Cleanup Docs Folder
  .github/PULL_REQUEST_TEMPLATE.md
  .github/docs/CONTRIBUTING.md
  .github/docs/SPRINT_PLANNING.md
  README.md
  docs/architecture/API_Design_V1.md
  docs/architecture/MVP_System_Design.md
  docs/assets/api-design-flowchart-source-code.md
  docs/assets/mvp-system-design-diagram.png
  docs/assets/screenshot-firebase-config.png
  docs/assets/screenshot-firebase-key.png
  docs/decisions/API_Design_Pattern_Decision_Log.md
  docs/decisions/Authentication_Flow_Decision_Log.md
  docs/decisions/Decision_Log_Template.md
  docs/decisions/End_to_End_Testing_Decision_Log.md
  docs/decisions/Knowledge_Graph_Visualization_Library_Decision_Log.md
  docs/decisions/LLM_Decision_Log.md
  docs/decisions/Rate_Limiting_Decision_Log.md
  docs/guides/deployment/nodeserver.service
  docs/guides/development/Commit_Message_Guide.md
  docs/guides/development/Contribution_Guide.md
  docs/guides/development/Developer_Onboarding_Guide.md
  docs/guides/development/How_To_Obtain_Gemini_Key.md
  docs/guides/development/How_To_Run_Cypress_E2E_Tests.md
  docs/guides/development/How_To_Set_Up_CICD.md
  docs/guides/development/How_To_Set_Up_Zustand_Stores.md
  docs/guides/development/Naming_Conventions_Guide.md
  docs/guides/development/Security_Best_Practices_Guide.md
  docs/guides/features/Snackbar_Notification_Feature_Guide.md
Labels: documentation

#430 Refactor: Edge Styles
  client/features/output-visualization-page/components/Flow.tsx
Labels: frontend, UI/UX, MVP Final Push

#431 Refactor: Node Style
  client/features/output-visualization-page/components/Flow.tsx
  client/features/output-visualization-page/components/LinktaNode.tsx
  client/styles/LinktaFlow.module.css
  client/styles/react-flow.css
Labels: bug, UI/UX, MVP Final Push

#409 Added Confirm Password Field to Sign Up Page
  client/features/auth-pages/ForgotPasswordPage.tsx
  client/features/auth-pages/PasswordUpdatePage.tsx
  client/features/auth-pages/SignUpPage.tsx
  client/validators/authSchemas.ts
  client/validators/validateUserPassword.ts
  client/validators/validateUseremail.ts
Labels: frontend, UI/UX, MVP Final Push
