Repository Linkta-org/core, pull requests merged in 2024-05, with the labels that each got.

#114 Chore/gh-95 config overhaul
  .eslintignore
  .eslintrc.json
  .husky/pre-commit
  .prettierrc.json
  client/components/layout/main-layout/header/LinktaLogoWithText.tsx
  client/components/layout/main-layout/header/TopNavigationBar.tsx
  client/config/firebaseWeb.ts
  client/index.html
  client/routes/ProtectedRoute.tsx
  client/vite.config.js
  package-lock.json
  package.json
  server/models/GeminiModel.ts
Labels: enhancement, urgent, unblocking, spike, configuration, sprint-0

#118 Base Linkta UI - Static Layout, Background Image, Side Nav Drawer
  .eslintignore
  .eslintrc.json
  .husky/pre-commit
  .prettierrc.json
  client/assets/linkta-logo-transparent.svg
  client/assets/white-tree.png
  client/components/layout/Footer.tsx
  client/components/layout/LinktaLogoWithText.tsx
  client/components/layout/MainLayout.tsx
  client/components/layout/TopNavigationBar.tsx
  client/components/layout/layoutConfig.ts
  client/components/layout/main-layout/MainLayout.tsx
  client/components/layout/main-layout/header/LinktaLogoWithText.tsx
  client/config/firebaseWeb.ts
  client/hooks/useDynamicNavigation.ts
  client/index.html
  client/main.tsx
  client/routes/ProtectedRoute.tsx
  client/routes/index.tsx
  client/styles/MainLayout.css
  client/styles/index.css
  client/utils/customTheme.ts
  client/vite.config.js
  package-lock.json
  package.json
  server/models/GeminiModel.ts
  server/models/LinktaFlowModel.ts
  server/models/UserInputModel.ts
  server/models/UserModel.ts
  server/types/datamodels.d.ts
  tsconfig.json
  utils/sanitizeInput.ts
  utils/zodSchema/userInputValidation.ts
Labels: frontend, UI/UX, design, styling, sprint-0

#111 Feature: Add MUI Snackbar with Alert to create a common notification component
  .eslintrc.json
  client/components/common/SnackBarNotification.tsx
Labels: enhancement, frontend, UI/UX, sprint-0

#119 implements userInputController and userInput route
  server/controllers/userInputController.ts
  server/routes/userInput.ts
Labels: backend, sprint-0

#137 Align API and System Design Docs with Sprint 0 Updates
  .github/docs/API_DESIGN_DOCUMENTATION_V1.md
  .github/docs/MVP_SYSTEM_DESIGN_DOCUMENTATION.md
  .github/docs/assets/api-design-flowchart-source-code.md
  .github/docs/assets/api-design-flowchart.png
Labels: documentation, sprint-0

#135 Feature/snackbar update
  client/components/common/SnackBarNotification.tsx
Labels: bug, frontend, UI/UX, design, sprint-1
